const apiKey = "AIzaSyAvzM-6pq1eLVZ0RrQbIwymMFjsvAirzfA";
const addresses = [
  "1002 Randall Drive, Rockford, IL, USA",
  "1008 Mayfair Place, Rockford, IL, USA",
  "1009 Woodland Drive, Rockford, IL, USA",
  "1012 McKnight Circle, Rockford, IL, USA",
  "1013 Olympia Lane, Rockford, IL, USA",
  "1016 Featherstone Road, Rockford, IL, USA",
  "1022 Nassau Parkway, Rockford, IL, USA",
  "1026 McKnight Circle, Rockford, IL, USA",
  "1055 Featherstone Road, Rockford, IL, USA",
  "106 Cherry Street, Cherry Valley, IL, USA",
  "109 North Show Place Drive, Rockford, IL, USA",
  "1100 North Lyford Road, Rockford, IL, USA",
  "1103 Kingsway Avenue, Rockford, IL, USA",
  "111 North Alpine Road, Rockford, IL, USA",
  "1110 Chelsea Avenue, Rockford, IL, USA",
  "1110 South Mulford Road, Rockford, IL, USA",
  "1111 South Alpine Road, Rockford, IL, USA",
  "1115 Easton Parkway, Rockford, IL, USA",
  "1130 South Alpine Road, Rockford, IL, USA",
  "1141 Arnold Avenue, Rockford, IL, USA",
  "1160 North Mulford Road, Rockford, IL, USA",
  "1165 Arnold Avenue, Rockford, IL, USA",
  "1165 Butler Road, Rockford, IL, USA",
  "1176 Trowbridge Lane, Rockford, IL, USA",
  "1177 Willowick Lane, Rockford, IL, USA",
  "1210 Prestwick Parkway, Rockford, IL, USA",
  "1220 Geneva Avenue, Rockford, IL, USA",
  "1224 Comanche Drive, Rockford, IL, USA",
  "1227 Roxbury Close, Rockford, IL, USA",
  "123 Hilton Avenue, Rockford, IL, USA",
  "123 North Alpine Road, Rockford, IL, USA",
  "1235 North Mulford Road, Rockford, IL, USA",
  "1243 Butler Road, Rockford, IL, USA",
  "1243 South Bell School Road, Rockford, IL, USA",
  "1252 Bell Valley Road, Rockford, IL, USA",
  "1266 North Crest Drive, Rockford, IL, USA",
  "1280 South Alpine Road, Rockford, IL, USA",
  "129 Phelps Avenue, Rockford, IL, USA",
  "1296 Tebala Boulevard, Rockford, IL, USA",
  "1304 Dixie Drive, Rockford, IL, USA",
  "1318 Stony Creek Way, Rockford, IL, USA",
  "1320 Livingston Drive, Rockford, IL, USA",
  "1332 University Drive, Rockford, IL, USA",
  "1372 Red Oak Lane, Rockford, IL, USA",
  "139 Warren Avenue, Rockford, IL, USA",
  "1401 North Bell School Road, Rockford, IL, USA",
  "1403 Stony Creek Way, Rockford, IL, USA",
  "1404 Turnbull Court, Rockford, IL, USA",
  "1408 Al Crest Road, Rockford, IL, USA",
  "1412 Arden Avenue, Rockford, IL, USA",
  "1413 Apache Drive, Rockford, IL, USA",
  "1431 Sandhurst Lane, Rockford, IL, USA",
  "1446 Red Oak Court, Rockford, IL, USA",
  "1453 Brandywine Drive, Rockford, IL, USA",
  "1463 South Bell School Road, Rockford, IL, USA",
  "1502 Livingston Drive, Rockford, IL, USA",
  "1507 Arden Avenue, Rockford, IL, USA",
  "1507 Gorham Place, Rockford, IL, USA",
  "1510 South Mulford Road, Rockford, IL, USA",
  "1520 Quentin Road, Rockford, IL, USA",
  "1545 Temple Lane, Rockford, IL, USA",
  "1585 Marshfield Drive, Rockford, IL, USA",
  "1595 South Bell School Road, Cherry Valley, IL, USA",
  "1604 Telemark Drive, Rockford, IL, USA",
  "1606 Lynnwood Street, Rockford, IL, USA",
  "1612 Cynthia Drive, Rockford, IL, USA",
  "1613 Valencia Drive, Rockford, IL, USA",
  "1634 White Oak Trail, Cherry Valley, IL, USA",
  "1639 North Alpine Road, Rockford, IL, USA",
  "1644 North Bell School Road, Rockford, IL, USA",
  "1649 Shaw Woods Drive, Rockford, IL, USA",
  "1698 Eden Place, Rockford, IL, USA",
  "1701 Duncan Avenue, Rockford, IL, USA",
  "1731 East Riverside Boulevard, Rockford, IL, USA",
  "1746 Shaw Woods Drive, Rockford, IL, USA",
  "175 Executive Parkway, Rockford, IL, USA",
  "1781 South Bell School Road, Cherry Valley, IL, USA",
  "1810 Larkspur Drive, Rockford, IL, USA",
  "1815 South Mulford Road, Rockford, IL, USA",
  "1818 Mill Road, Cherry Valley, IL, USA",
  "1820 Hawthorne Drive, Rockford, IL, USA",
  "1832 Bright View Drive, Loves Park, IL, USA",
  "1858 Bright View Drive, Loves Park, IL, USA",
  "1860 Wedgewood Way, Rockford, IL, USA",
  "1865 Honeysuckle Drive, Rockford, IL, USA",
  "1869 North Perryville Road, Rockford, IL, USA",
  "187 Flintridge Drive, Rockford, IL, USA",
  "1870 North Perryville Road, Rockford, IL, USA",
  "1899 North Perryville Road, Rockford, IL, USA",
  "190 Buckley Drive, Rockford, IL, USA",
  "1902 Reid Farm Road, Rockford, IL, USA",
  "1904 Sweetbriar Lane, Rockford, IL, USA",
  "1908 Hillcrest Road, Rockford, IL, USA",
  "1911 Santa Monica Drive, Rockford, IL, USA",
  "1949 South Bell School Road, Rockford, IL, USA",
  "1951 Valencia Drive, Rockford, IL, USA",
  "1957 Pawlisch Drive, Rockford, IL, USA",
  "199 Deane Drive, Rockford, IL, USA",
  "1998 McFarland Road, Rockford, IL, USA",
  "200 South Bell School Road, Rockford, IL, USA",
  "2001 South Perryville Road, Rockford, IL, USA",
  "2002 South Mulford Road, Rockford, IL, USA",
  "2004 Azure Court, Rockford, IL, USA",
  "2006 Spring Brook Avenue, Rockford, IL, USA",
  "2022 Wilcox Road, Rockford, IL, USA",
  "2051 Wembley Place, Rockford, IL, USA",
  "206 West State Street, Cherry Valley, IL, USA",
  "2066 Villanova Drive, Rockford, IL, USA",
  "2071 North Mulford Road, Rockford, IL, USA",
  "2096 Valencia Drive, Rockford, IL, USA",
  "2106 Delcy Drive, Rockford, IL, USA",
  "2136 Mariposa Drive, Rockford, IL, USA",
  "2165 Carrington Chase, Rockford, IL, USA",
  "2204 Winnetka Drive, Rockford, IL, USA",
  "2208 Grandchester Place, Rockford, IL, USA",
  "221 North Alpine Road, Rockford, IL, USA",
  "2212 Grandchester Place, Rockford, IL, USA",
  "2218 North Mulford Road, Rockford, IL, USA",
  "2235 Forest View Road, Rockford, IL, USA",
  "2238 Chenowith Court, Rockford, IL, USA",
  "224 Calvin Park Boulevard North, Rockford, IL, USA",
  "224 North Alpine Road, Rockford, IL, USA",
  "2241 South Perryville Road, Rockford, IL, USA",
  "2243 Shillington Drive, Rockford, IL, USA",
  "2243 Silverthorn Drive, Rockford, IL, USA",
  "226 North Alpine Road, Rockford, IL, USA",
  "227 North Alpine Road, Rockford, IL, USA",
  "2295 Mariposa Drive, Rockford, IL, USA",
  "2325 Silverthorn Drive, Rockford, IL, USA",
  "2328 Eggleston Road, Rockford, IL, USA",
  "2334 Edgebrook Drive, Rockford, IL, USA",
  "235 Skylark Drive, Rockford, IL, USA",
  "236 North Phelps Avenue, Rockford, IL, USA",
  "2404 South Perryville Road, Rockford, IL, USA",
  "2475 North Perryville Road, Rockford, IL, USA",
  "249 Deane Drive, Rockford, IL, USA",
  "2510 Holmes Street, Rockford, IL, USA",
  "2519 Sandhutton Avenue, Rockford, IL, USA",
  "2549 Woodmar Road, Rockford, IL, USA",
  "2550 South Alpine Road, Rockford, IL, USA",
  "2601 Reid Farm Road, Rockford, IL, USA",
  "2635 Tuck-A-Way Trail, Rockford, IL, USA",
  "2640 Ashwin Boulevard, Rockford, IL, USA",
  "2653 Point O Woods Drive, Rockford, IL, USA",
  "2674 Woodmar Road, Rockford, IL, USA",
  "2696 McFarland Road, Rockford, IL, USA",
  "2721 Bordeaux Drive, Rockford, IL, USA",
  "273 Joyce Avenue, Rockford, IL, USA",
  "2735 Stowmarket Avenue, Rockford, IL, USA",
  "275 North Phelps Avenue, Rockford, IL, USA",
  "277 Deane Drive, Rockford, IL, USA",
  "2787 McFarland Road, Rockford, IL, USA",
  "2790 Sandhutton Avenue, Rockford, IL, USA",
  "281 Deane Drive, Rockford, IL, USA",
  "2824 Soland Drive, Rockford, IL, USA",
  "2825 English Lane, Rockford, IL, USA",
  "2889 Kregel Drive, Rockford, IL, USA",
  "2902 McFarland Road, Rockford, IL, USA",
  "2902 Stowmarket Avenue, Rockford, IL, USA",
  "2911 Canyon Woods Drive, Rockford, IL, USA",
  "2955 Swanson Parkway, Rockford, IL, USA",
  "3011 North Perryville Road, Rockford, IL, USA",
  "3015 North Perryville Road, Rockford, IL, USA",
  "302 North Alpine Road, Rockford, IL, USA",
  "3062 Chartwell Court, Rockford, IL, USA",
  "3065 North Perryville Road, Rockford, IL, USA",
  "3130 Stowmarket Avenue, Rockford, IL, USA",
  "315 Bienterra Trail, Rockford, IL, USA",
  "3154 McFarland Road, Rockford, IL, USA",
  "3155 McFarland Road, Rockford, IL, USA",
  "316 North Alpine Road, Rockford, IL, USA",
  "316 Palm Avenue, Rockford, IL, USA",
  "3175 Tuggle Drive, Cherry Valley, IL, USA",
  "3207 Pecan Street, Rockford, IL, USA",
  "3220 Spring Lake Drive, Rockford, IL, USA",
  "324 Roxbury Road, Rockford, IL, USA",
  "3248 Forest View Road, Rockford, IL, USA",
  "3256 Andover Drive, Rockford, IL, USA",
  "3296 North Trainer Road, Rockford, IL, USA",
  "3301 North Mulford Road, Rockford, IL, USA",
  "3302 McFarland Road, Rockford, IL, USA",
  "3304 Windsong Court, Rockford, IL, USA",
  "3319 Conover Drive, Rockford, IL, USA",
  "3333 Burlwood Drive, Rockford, IL, USA",
  "3364 Cavendish Court, Rockford, IL, USA",
  "3369 Montlake Drive, Rockford, IL, USA",
  "3392 East Summerfield Drive, Rockford, IL, USA",
  "3401 North Perryville Road, Rockford, IL, USA",
  "341 Bienterra Trail, Rockford, IL, USA",
  "345 Bienterra Trail, Rockford, IL, USA",
  "3451 Fawnridge Drive, Rockford, IL, USA",
  "3455 South Mulford Road, Rockford, IL, USA",
  "346 Roxbury Road, Rockford, IL, USA",
  "3479 East Summerfield Drive, Rockford, IL, USA",
  "3502 East State Street, Rockford, IL, USA",
  "3505 North Bell School Road, Rockford, IL, USA",
  "3525 Spring Creek Road, Rockford, IL, USA",
  "3535 North Bell School Road, Rockford, IL, USA",
  "3559 Shelburne Drive, Rockford, IL, USA",
  "3567 White Dove Lane, Rockford, IL, USA",
  "3607 Oak Grove Avenue, Rockford, IL, USA",
  "3611 Crosby Street, Rockford, IL, USA",
  "3617 Applewood Lane, Rockford, IL, USA",
  "363 Financial Court, Rockford, IL, USA",
  "3778 East State Street, Rockford, IL, USA",
  "3800 East State Street, Rockford, IL, USA",
  "3809 Sage Drive, Rockford, IL, USA",
  "3811 Brendenwood Road, Rockford, IL, USA",
  "3815 North Trainer Road, Rockford, IL, USA",
  "3819 Pinecrest Road, Rockford, IL, USA",
  "3834 Abbotsford Road, Rockford, IL, USA",
  "3854 Thyme Drive, Rockford, IL, USA",
  "386 Bancroft Court, Rockford, IL, USA",
  "387 Brett Place, Rockford, IL, USA",
  "3901 Brendenwood Road, Rockford, IL, USA",
  "3910 Marsh Avenue, Rockford, IL, USA",
  "4001 North Mulford Road, Loves Park, IL, USA",
  "4004 Barley Ridge Trail, Cherry Valley, IL, USA",
  "4004 Crestview Drive, Rockford, IL, USA",
  "4007 Shirley Road, Rockford, IL, USA",
  "401 Roxbury Road, Rockford, IL, USA",
  "401 Westchester Drive, Rockford, IL, USA",
  "4013 Guilford Road, Rockford, IL, USA",
  "4015 Highcrest Road, Rockford, IL, USA",
  "4040 East State Street, Rockford, IL, USA",
  "405 Cross Plains Road, Rockford, IL, USA",
  "4054 Renn Hart Hills, Loves Park, IL, USA",
  "4055 South Perryville Road, Cherry Valley, IL, USA",
  "4060 Rock Valley Parkway, Loves Park, IL, USA",
  "4100 North Perryville Road, Loves Park, IL, USA",
  "4103 Highcrest Road, Rockford, IL, USA",
  "412 Amphitheater Drive, Rockford, IL, USA",
  "4175 Split Leaf Drive, Loves Park, IL, USA",
  "4176 Old Golf Road, Loves Park, IL, USA",
  "418 Amphitheater Drive, Rockford, IL, USA",
  "4201 Galleria Drive, Loves Park, IL, USA",
  "4224 Maray Drive, Rockford, IL, USA",
  "4234 River Hawk Drive, Loves Park, IL, USA",
  "4249 East State Street, Rockford, IL, USA",
  "425 Roxbury Road, Rockford, IL, USA",
  "426 South Lyford Road, Rockford, IL, USA",
  "428 Amphitheater Drive, Rockford, IL, USA",
  "4304 East State Street, Rockford, IL, USA",
  "4305 Kingsbury Drive, Loves Park, IL, USA",
  "4312 Dorset Drive, Rockford, IL, USA",
  "4312 East State Street, Rockford, IL, USA",
  "4317 Maray Drive, Rockford, IL, USA",
  "4320 Morsay Drive, Rockford, IL, USA",
  "4338 Morsay Drive, Rockford, IL, USA",
  "4352 Denise Drive, Loves Park, IL, USA",
  "4361 Kellee Lane, Loves Park, IL, USA",
  "4371 Sunset Terrace, Loves Park, IL, USA",
  "4400 Eastridge Drive, Rockford, IL, USA",
  "4401 Peak Drive, Loves Park, IL, USA",
  "4402 Peak Drive, Loves Park, IL, USA",
  "444 Roxbury Road, Rockford, IL, USA",
  "4449 Charles Street, Rockford, IL, USA",
  "4455 Charles Street, Rockford, IL, USA",
  "4502 Charles Street, Rockford, IL, USA",
  "4508 Applewood Lane, Loves Park, IL, USA",
  "4510 Erickson Drive, Rockford, IL, USA",
  "4531 Squaw Valley Drive, Loves Park, IL, USA",
  "4546 Galleon Drive, Loves Park, IL, USA",
  "4560 Apple Orchard Lane, Rockford, IL, USA",
  "4607 Marion Avenue, Rockford, IL, USA",
  "4615 East State Street, Rockford, IL, USA",
  "4617 Sandy Hollow Road, Rockford, IL, USA",
  "4629 Fenton Lane, Loves Park, IL, USA",
  "4632 Newburg Road, Rockford, IL, USA",
  "4640 Pembrooke Place, Rockford, IL, USA",
  "4685 High Point Drive, Rockford, IL, USA",
  "4702 White Oak Avenue, Rockford, IL, USA",
  "4705 Cromwell Lane, Loves Park, IL, USA",
  "4707 Birch Avenue, Rockford, IL, USA",
  "4708 Stonegate Place, Rockford, IL, USA",
  "4709 Manheim Road, Rockford, IL, USA",
  "4710 Stonegate Place, Rockford, IL, USA",
  "4747 Harrison Avenue, Rockford, IL, USA",
  "4808 Crescent Drive, Rockford, IL, USA",
  "4809 Javelin Drive, Rockford, IL, USA",
  "4811 Snowcap Run, Loves Park, IL, USA",
  "4822 Orchard Avenue, Rockford, IL, USA",
  "484 Tralee Drive, Rockford, IL, USA",
  "4860 Fenwick Close, Rockford, IL, USA",
  "4867 Pine Meadow Parkway, Loves Park, IL, USA",
  "4920 Arbutus Road, Rockford, IL, USA",
  "494 Bienterra Trail, Rockford, IL, USA",
  "4940 East State Street, Rockford, IL, USA",
  "4949 Harrison Avenue, Rockford, IL, USA",
  "4990 East State Street, Rockford, IL, USA",
  "4998 East State Street, Rockford, IL, USA",
  "5036 Arbutus Road, Rockford, IL, USA",
  "5040 Norwich Drive, Rockford, IL, USA",
  "505 North Perryville Road, Rockford, IL, USA",
  "5050 East State Street, Rockford, IL, USA",
  "5104 Wil-Acre Drive, Loves Park, IL, USA",
  "5121 East State Street, Rockford, IL, USA",
  "5124 Parliament Place, Rockford, IL, USA",
  "5145 East State Street, Rockford, IL, USA",
  "5161 Potomac Drive, Rockford, IL, USA",
  "5199 Woodie Ranch Lane, Rockford, IL, USA",
  "5206 Arbutus Road, Rockford, IL, USA",
  "5213 26th Avenue, Rockford, IL, USA",
  "5218 Wil-Acre Drive, Loves Park, IL, USA",
  "5220 Conrad Avenue, Rockford, IL, USA",
  "5234 Regents Park Road, Rockford, IL, USA",
  "524 Featherstone Road, Rockford, IL, USA",
  "5259 Indianhead Avenue, Rockford, IL, USA",
  "5274 Pepper Drive, Rockford, IL, USA",
  "5301 East State Street, Rockford, IL, USA",
  "5318 Parliament Place, Rockford, IL, USA",
  "5338 Cybele Lane, Rockford, IL, USA",
  "5361 Pierce Lake Drive, Caledonia, IL, USA",
  "542 North Lyford Road, Rockford, IL, USA",
  "5430 Regents Park Road, Rockford, IL, USA",
  "5451 East State Street, Rockford, IL, USA",
  "5471 Roanoke Road, Rockford, IL, USA",
  "5485 East State Street, Rockford, IL, USA",
  "5505 East State Street, Rockford, IL, USA",
  "5509 Heidi Drive, Rockford, IL, USA",
  "5514 Ponderosa Drive, Rockford, IL, USA",
  "5517 Sedgeway Drive, Rockford, IL, USA",
  "5524 Shaw Woods Close, Rockford, IL, USA",
  "5526 Providence Forge, Rockford, IL, USA",
  "5535 Providence Forge, Rockford, IL, USA",
  "5547 Haddon Place, Rockford, IL, USA",
  "5555 Raspberry Trail, Rockford, IL, USA",
  "5568 East State Street, Rockford, IL, USA",
  "557 South Newtowne Drive, Rockford, IL, USA",
  "5577 Whispering Way, Loves Park, IL, USA",
  "5580 Stockton Drive, Rockford, IL, USA",
  "560 Schauer Lane, Rockford, IL, USA",
  "5603 East State Street, Rockford, IL, USA",
  "5610 Knollwood Road, Rockford, IL, USA",
  "5620 Spring Creek Road, Rockford, IL, USA",
  "5626 Pepper Drive, Rockford, IL, USA",
  "5639 Haddon Place, Rockford, IL, USA",
  "5643 East State Street, Rockford, IL, USA",
  "5666 East State Street, Rockford, IL, USA",
  "5668 East State Street, Rockford, IL, USA",
  "5685 Coachman Court, Rockford, IL, USA",
  "5695 East State Street, Rockford, IL, USA",
  "5703 Inverness Drive, Rockford, IL, USA",
  "5725 Knollwood Road, Rockford, IL, USA",
  "5730 Strathmoor Drive, Rockford, IL, USA",
  "5757 Inverness Drive, Rockford, IL, USA",
  "5801 Columbia Parkway, Rockford, IL, USA",
  "5807 Garrett Lane, Rockford, IL, USA",
  "5824 East State Street, Rockford, IL, USA",
  "5827 Chandler Drive, Rockford, IL, USA",
  "5827 Vineyard Lane, Rockford, IL, USA",
  "5830 Garrett Lane, Rockford, IL, USA",
  "5844 Elaine Drive, Rockford, IL, USA",
  "5850 Garrett Lane, Rockford, IL, USA",
  "5850 Strathmoor Drive, Rockford, IL, USA",
  "5875 East Riverside Boulevard, Rockford, IL, USA",
  "588 South Perryville Road, Rockford, IL, USA",
  "5901 Sandringham Lane, Rockford, IL, USA",
  "5904 Clarendon Drive, Rockford, IL, USA",
  "5905 Thatcher Drive, Rockford, IL, USA",
  "5915 East Riverside Boulevard, Rockford, IL, USA",
  "5919 Spring Creek Road, Rockford, IL, USA",
  "5937 Sandy Hollow Road, Rockford, IL, USA",
  "5945 Whispering Way, Loves Park, IL, USA",
  "5950 Spring Creek Road, Rockford, IL, USA",
  "5962 Fox Basin Road, Rockford, IL, USA",
  "5965 Chandler Drive, Rockford, IL, USA",
  "5970 Churchview Drive, Rockford, IL, USA",
  "5984 Durrington Drive, Loves Park, IL, USA",
  "5995 Spring Creek Road, Rockford, IL, USA",
  "6007 East State Street, Rockford, IL, USA",
  "603 Hemlock Lane, Rockford, IL, USA",
  "6030 Garrett Lane, Rockford, IL, USA",
  "6036 Fox Basin Road, Rockford, IL, USA",
  "6042 Boxwood Drive, Rockford, IL, USA",
  "6066 Strathmoor Drive, Rockford, IL, USA",
  "6072 Brynwood Drive, Rockford, IL, USA",
  "6075 East State Street, Rockford, IL, USA",
  "6079 East Riverside Boulevard, Rockford, IL, USA",
  "6079 Nimtz Court, Loves Park, IL, USA",
  "6090 East State Street, Rockford, IL, USA",
  "610 North Bell School Road, Rockford, IL, USA",
  "6104 Cranbrook Lane, Rockford, IL, USA",
  "6118 Boxwood Drive, Rockford, IL, USA",
  "6130 East Riverside Boulevard, Loves Park, IL, USA",
  "6139 Fox Basin Road, Rockford, IL, USA",
  "615 Clark Drive, Rockford, IL, USA",
  "6150 Buttercup Lane, Rockford, IL, USA",
  "6153 Muirfield Lane, Rockford, IL, USA",
  "6156 East Riverside Boulevard, Loves Park, IL, USA",
  "6206 Brynwood Drive, Rockford, IL, USA",
  "6216 Buttercup Lane, Rockford, IL, USA",
  "6218 Fireside Drive, Rockford, IL, USA",
  "6239 East State Street, Rockford, IL, USA",
  "6242 East State Street, Rockford, IL, USA",
  "6249 East State Street, Rockford, IL, USA",
  "6253 East State Street, Rockford, IL, USA",
  "6301 East State Street, Rockford, IL, USA",
  "631 Par Place, Belvidere, IL, USA",
  "6310 East State Street, Rockford, IL, USA",
  "6320 East State Street, Rockford, IL, USA",
  "6322 Grassridge Road, Rockford, IL, USA",
  "6325 East State Street, Rockford, IL, USA",
  "633 North Bell School Road, Rockford, IL, USA",
  "6335 East State Street, Rockford, IL, USA",
  "6346 Oak Crest Lane, Loves Park, IL, USA",
  "6355 Muirfield Lane, Rockford, IL, USA",
  "6360 Lyndhurst Lane, Rockford, IL, USA",
  "6373 East State Street, Rockford, IL, USA",
  "6377 Garrett Lane, Rockford, IL, USA",
  "6381 Maeve Lane, Rockford, IL, USA",
  "6387 East State Street, Rockford, IL, USA",
  "6395 Wicklow Close, Rockford, IL, USA",
  "6414 Garrett Lane, Rockford, IL, USA",
  "6449 East State Street, Rockford, IL, USA",
  "6451 East State Street, Rockford, IL, USA",
  "6479 Maeve Lane, Rockford, IL, USA",
  "648 Shiloh Road, Rockford, IL, USA",
  "653 Featherstone Road, Rockford, IL, USA",
  "6541 Abington Drive, Rockford, IL, USA",
  "6555 East State Street, Rockford, IL, USA",
  "6560 East State Street, Rockford, IL, USA",
  "6565 East State Street, Rockford, IL, USA",
  "6585 East State Street, Rockford, IL, USA",
  "6595 Guilford Road, Rockford, IL, USA",
  "6600 East Riverside Boulevard, Loves Park, IL, USA",
  "6602 East State Street, Rockford, IL, USA",
  "6602 Thomas Parkway, Rockford, IL, USA",
  "6618 Sonoma Road, Rockford, IL, USA",
  "6626 East State Street, Rockford, IL, USA",
  "6627 Torch Lite Trail, Loves Park, IL, USA",
  "6630 Spring Brook Road, Rockford, IL, USA",
  "6640 East State Street, Rockford, IL, USA",
  "6673 Laurel Cherry Drive, Rockford, IL, USA",
  "670 Shiloh Road, Rockford, IL, USA",
  "6741 Leaoak Drive, Rockford, IL, USA",
  "6743 Samantha Lane, Rockford, IL, USA",
  "6749 Hedgewood Road, Rockford, IL, USA",
  "6758 Guilford Road, Rockford, IL, USA",
  "6765 Thomas Parkway, Rockford, IL, USA",
  "6774 Troy Drive, Rockford, IL, USA",
  "6801 Mill Road, Rockford, IL, USA",
  "6801 Spring Creek Road, Rockford, IL, USA",
  "6804 Academy Trail, Rockford, IL, USA",
  "6833 Cardigan Way, Rockford, IL, USA",
  "6838 East State Street, Rockford, IL, USA",
  "6845 Weaver Road, Rockford, IL, USA",
  "6861 Villagreen View, Rockford, IL, USA",
  "6910 Argus Drive, Rockford, IL, USA",
  "6916 Tupelo Road, Loves Park, IL, USA",
  "6917 Cardigan Way, Rockford, IL, USA",
  "6929 East State Street, Rockford, IL, USA",
  "6930 Argus Drive, Rockford, IL, USA",
  "6943 East State Street, Rockford, IL, USA",
  "695 North Perryville Road, Rockford, IL, USA",
  "6952 Rote Road, Rockford, IL, USA",
  "6972 Olde Creek Road, Rockford, IL, USA",
  "698 Featherstone Road, Rockford, IL, USA",
  "7005 Golden Eagle Drive, Loves Park, IL, USA",
  "701 Coolidge Place, Rockford, IL, USA",
  "7012 Thomas Drive, Loves Park, IL, USA",
  "7019 Rote Road, Rockford, IL, USA",
  "7051 Fincham Drive, Rockford, IL, USA",
  "7053 Golden Eagle Drive, Loves Park, IL, USA",
  "7070 Cherryvale North Boulevard, Rockford, IL, USA",
  "7078 Sentinel Road, Rockford, IL, USA",
  "7120 Forest Glen Drive, Rockford, IL, USA",
  "7151 Walton Street, Rockford, IL, USA",
  "7160 Harrison Avenue, Rockford, IL, USA",
  "7171 Cherryvale North Boulevard, Rockford, IL, USA",
  "7186 Colosseum Drive, Rockford, IL, USA",
  "7190 East Riverside Boulevard, Loves Park, IL, USA",
  "7200 Harrison Avenue, Rockford, IL, USA",
  "7209 Brimmer Way, Cherry Valley, IL, USA",
  "7217 Golden Eagle Drive, Loves Park, IL, USA",
  "7218 Sentinel Road, Rockford, IL, USA",
  "7240 Sue Lane, Loves Park, IL, USA",
  "7243 Cherryvale North Boulevard, Rockford, IL, USA",
  "725 North Lyford Road, Rockford, IL, USA",
  "7250 Montmorency Drive, Rockford, IL, USA",
  "7260 Sue Lane, Loves Park, IL, USA",
  "7261 Wheatland Terrace, Cherry Valley, IL, USA",
  "7264 Argus Drive, Rockford, IL, USA",
  "7270 Sue Lane, Loves Park, IL, USA",
  "7281 Olde Creek Road, Rockford, IL, USA",
  "7292 Thomas Drive, Loves Park, IL, USA",
  "7295 Forest Glen Drive, Rockford, IL, USA",
  "730 North Lyford Road, Rockford, IL, USA",
  "7310 Walton Street, Rockford, IL, USA",
  "7312 Ashton Villa, Rockford, IL, USA",
  "7318 Chucks Way, Loves Park, IL, USA",
  "7320 Meander Drive, Rockford, IL, USA",
  "7322 Argus Drive, Rockford, IL, USA",
  "7326 North Cherryvale Mall Drive, Rockford, IL, USA",
  "7337 Bermuda Drive, Rockford, IL, USA",
  "7347 Shillington Drive, Rockford, IL, USA",
  "735 North Perryville Road, Rockford, IL, USA",
  "7351 Mill Road, Rockford, IL, USA",
  "7351 Vanista Court, Rockford, IL, USA",
  "7366 Travertine Trail, Rockford, IL, USA",
  "7370 East State Street, Rockford, IL, USA",
  "7373 Harrison Avenue, Rockford, IL, USA",
  "740 Tulip Lane, Rockford, IL, USA",
  "7408 Wallingford Way, Rockford, IL, USA",
  "7414 Wallingford Way, Rockford, IL, USA",
  "7424 Shillington Drive, Rockford, IL, USA",
  "7431 Fairmont Lane, Rockford, IL, USA",
  "747 North Bell School Road, Rockford, IL, USA",
  "7474 East State Street, Rockford, IL, USA",
  "7476 Countryshire Lane, Rockford, IL, USA",
  "7500 East Riverside Boulevard, Loves Park, IL, USA",
  "7539 Creek Bend, Rockford, IL, USA",
  "7545 Marsh Hawk Drive, Loves Park, IL, USA",
  "755 South Mulford Road, Rockford, IL, USA",
  "7550 East State Street, Rockford, IL, USA",
  "7606 Blairmore Drive, Rockford, IL, USA",
  "7610 Ivory Lane, Rockford, IL, USA",
  "7614 Magnolia Trail, Cherry Valley, IL, USA",
  "7632 Cherryvale North Boulevard, Cherry Valley, IL, USA",
  "7640 Cherryvale North Boulevard, Cherry Valley, IL, USA",
  "7675 Walton Street, Rockford, IL, USA",
  "7676 East State Street, Rockford, IL, USA",
  "7691 Lloyd Drive, Cherry Valley, IL, USA",
  "7740 Shaw Road, Belvidere, IL, USA",
  "7887 Timber Trail Road, Rockford, IL, USA",
  "7992 Royal Oaks Road, Rockford, IL, USA",
  "801 North Perryville Road, Rockford, IL, USA",
  "8042 Slater Drive, Rockford, IL, USA",
  "805 Midlothian Way, Rockford, IL, USA",
  "806 East State Street, Cherry Valley, IL, USA",
  "8071 Rosemeade Lane, Rockford, IL, USA",
  "8078 Cloverdale Lane, Rockford, IL, USA",
  "8101 Sayer Road, Rockford, IL, USA",
  "816 Featherstone Road, Rockford, IL, USA",
  "8201 East Riverside Boulevard, Loves Park, IL, USA",
  "8279 Wilrich Drive, Belvidere, IL, USA",
  "833 Featherstone Road, Rockford, IL, USA",
  "8331 Alaska Road, Rockford, IL, USA",
  "839 North Perryville Road, Rockford, IL, USA",
  "8431 Jamesport Drive, Rockford, IL, USA",
  "8508 Jamesport Drive, Rockford, IL, USA",
  "8525 Greenport Way, Rockford, IL, USA",
  "8565 Jamesport Drive, Rockford, IL, USA",
  "8591 Autumn Lane, Rockford, IL, USA",
  "8616 Northern Avenue, Rockford, IL, USA",
  "8656 Grove Hill Road, Rockford, IL, USA",
  "8706 Olson Road, Belvidere, IL, USA",
  "8722 West Ridge Drive, Belvidere, IL, USA",
  "8881 Putter Place, Belvidere, IL, USA",
  "9142 Meadowsweet Drive, Belvidere, IL, USA",
  "924 Blenheim Drive, Rockford, IL, USA",
  "9253 Easton View Lane, Rockford, IL, USA",
  "929 South Alpine Road, Rockford, IL, USA",
  "963 South Trainer Road, Rockford, IL, USA",
  "9695 Ridgeview Road, Belvidere, IL, USA",
  "9900 Springborough Drive, Rockford, IL, USA",
  "991 South Perryville Road, Rockford, IL, USA",
];

function initMap() {
  // Initialize the map
  const map = new google.maps.Map(document.getElementById("map"), {
    center: { lat: 42.27088, lng: -88.979198 },
    zoom: 15,
  });

  // Geocode and display each address on the map
  addresses.forEach((address) => {
    const geocoder = new google.maps.Geocoder();
    geocoder.geocode({ address: address }, (results, status) => {
      if (status === "OK") {
        const marker = new google.maps.Marker({
          map: map,
          position: results[0].geometry.location,
          title: address,
          icon: {
            url: "http://maps.google.com/mapfiles/ms/icons/red-dot.png", // You can use a different URL or customize the marker image
            scaledSize: new google.maps.Size(32, 32), // Set the desired size
          },
        });
        marker.addListener("click", () => {
          // Show an info window with the address when the marker is clicked
          const infoWindow = new google.maps.InfoWindow({
            content: address,
          });
          infoWindow.open(map, marker);
        });
      } else {
        console.error(
          "Geocode was not successful for the following reason: " + status
        );
      }
    });
  });
}
